### ISSUE TITLE
 The system cannot find the file AndroidManifest.xml

### ISSUE THREAD

**Issue by ShinjiTwo** [HerokeyVN/Auto-clone-Canvas#1]
![image_2024-07-12_163249862](https://github.com/user-attachments/assets/343c1ef3-af6a-4e6f-9f09-f03a19d60041)

**Comment by HerokeyVN** [comment]
Hmmm, have you added the canvas.apk file to the working directory. Can you show me the “Batch Tool Auto Clone Canvas” folder?

**Comment by ShinjiTwo** [comment]
![image](https://github.com/user-attachments/assets/2f979515-7dd5-497b-b124-f3c3d21b0890)
![image](https://github.com/user-attachments/assets/ac7e4c8b-e664-4cb0-b296-21fca02b7721)

here is the folder along with the setting required, I don't know what happened

**Comment by HerokeyVN** [comment]
Sorry I've been a bit busy lately so I can't assist you right away. You can try right-clicking on the “main.bat” file and selecting “Run as administrator”. If the error still occurs, you can move the “Batch Tool Auto Clone Canvas” folder to another place and try again.

**Comment by ShinjiTwo** [comment]
tried both method, ain't working.
If yours still working then maybe this Github haven't been updated

**Comment by HerokeyVN** [comment]
Have you installed Java on your computer yet? Java is required for this script to work.

**Comment by ShinjiTwo** [comment]
> Have you installed Java on your computer yet? Java is required for this script to work.

I had java installed, latest. Does this Git need a specific version to work ?

**Comment by HerokeyVN** [comment]
This is so strange. This script works with all Canvas versions

**Comment by ShinjiTwo** [comment]
Wait is this working for Windows 11?

**Comment by HerokeyVN** [comment]
Support windows operating system (7/8.1/10/11)

You can try it on another computer, I tried checking the code again and couldn't find the bugs 🥲

**Comment by ShinjiTwo** [comment]
Can you fix it for me, I dm'ed you on Discord as shinji_5479

**Comment by HerokeyVN** [comment]
Done.
